import { AppUser } from '../types';

export const DEFAULT_PASSWORD = '123';
export const ADMIN_PASSWORD = 'admin123';

export const INITIAL_USERS: AppUser[] = [
  {
    stt: 0,
    hoTen: 'Quản trị viên Hệ thống',
    maNv: 'ADMIN01',
    user: 'admin',
    password: ADMIN_PASSWORD,
    phongBan: 'Quản trị hệ thống',
    viTri: 'Quản trị viên cấp cao',
    sdt: '0943882109',
    email: 'trongduc.ict@gmail.com',
    role: 'ADMIN',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 1,
    hoTen: 'Đinh Xuân Thắng',
    maNv: '00005568',
    user: 'thangdx',
    password: DEFAULT_PASSWORD,
    phongBan: 'Ban giám đốc',
    viTri: 'Giám đốc CN',
    sdt: '0979792099',
    email: 'THANGDX@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 2,
    hoTen: 'Bùi Thị Thu Dung',
    maNv: '00006961',
    user: 'dung.bt',
    password: DEFAULT_PASSWORD,
    phongBan: 'Ban giám đốc',
    viTri: 'Phó Giám đốc CN (KHDN)',
    sdt: '0945040477',
    email: 'DUNG.BT@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 3,
    hoTen: 'Đoàn Mạnh Dương',
    maNv: '00006962',
    user: 'duongdm',
    password: DEFAULT_PASSWORD,
    phongBan: 'Ban giám đốc',
    viTri: 'Phó Giám đốc Đầu mối Bán lẻ',
    sdt: '0915518668',
    email: 'DUONGDM@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 4,
    hoTen: 'Lý Hoàng Hà',
    maNv: '00006983',
    user: 'lyhoang.ha',
    password: DEFAULT_PASSWORD,
    phongBan: 'Ban giám đốc',
    viTri: 'Phó Giám đốc CN (KHDN)',
    sdt: '0912773043',
    email: 'LYHOANG.HA@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 5,
    hoTen: 'Nguyễn Thị Thu Hường',
    maNv: '00006949',
    user: 'huongntt400',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Hậu kiểm',
    sdt: '0916502028',
    email: 'HUONGNTT400@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 6,
    hoTen: 'Đinh Thanh Hà',
    maNv: '00006965',
    user: 'ha.dinhthanh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Trưởng phòng TCTH',
    sdt: '0903261126',
    email: 'HA.DINHTHANH@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 7,
    hoTen: 'Nguyễn Hữu Giáp',
    maNv: '00006966',
    user: 'giapnh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Nhân viên thu nợ',
    sdt: '0906685123',
    email: 'GIAPNH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 8,
    hoTen: 'Tạ Quang Thức',
    maNv: '00006970',
    user: 'thuctq',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Phó phòng TCTH',
    sdt: '0977879119',
    email: 'THUCTQ@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 9,
    hoTen: 'Nguyễn Hoàng Quỳnh',
    maNv: '00006975',
    user: 'quynhnh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Phó phòng TCTH',
    sdt: '0912852378',
    email: 'QUYNHNH@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 10,
    hoTen: 'Nguyễn Thị Thu Trà',
    maNv: '00006989',
    user: 'tra.ntt',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Nhân viên nhân sự tiền lương',
    sdt: '0917352681',
    email: 'TRA.NTT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 11,
    hoTen: 'Phạm Văn Minh',
    maNv: '00021947',
    user: 'pvminh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Lái xe',
    sdt: '0945959262',
    email: 'PVMINH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 12,
    hoTen: 'Vũ Thị Lan Phương',
    maNv: '00021948',
    user: 'phuongvtl',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Nhân viên văn thư',
    sdt: '0988266628',
    email: 'PHUONGVTL@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 13,
    hoTen: 'Trịnh Tuấn Dũng',
    maNv: '00028447',
    user: 'dungtt6',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Lái xe',
    sdt: '0975813868',
    email: 'DUNGTT6@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 14,
    hoTen: 'Đỗ Thị Thêm',
    maNv: '00043022',
    user: 'themdt',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng TCTH',
    viTri: 'Hậu kiểm',
    sdt: '0966017286',
    email: 'THEMDT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 15,
    hoTen: 'Đinh Quang Dân',
    maNv: '00006935',
    user: 'dandq',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Phó phòng Dịch vụ KH (TTKQ)',
    sdt: '0947676868',
    email: 'DANDQ@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 16,
    hoTen: 'Phạm Thị Hà',
    maNv: '00006948',
    user: 'pthiha',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Trưởng phòng Dịch vụ KH',
    sdt: '0915209091',
    email: 'PTHIHA@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 17,
    hoTen: 'Đỗ Thị Huế',
    maNv: '00006950',
    user: 'dt.hue',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Phó phòng Dịch vụ KH (Kế toán)',
    sdt: '0945268885',
    email: 'DT.HUE@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 18,
    hoTen: 'Nguyễn Minh Vũ',
    maNv: '00006959',
    user: 'vunm',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Thủ quỹ',
    sdt: '0838608888',
    email: 'VUNM@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 19,
    hoTen: 'Lương Thị Kim Liên',
    maNv: '00006978',
    user: 'lien.ltk',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Thủ quỹ',
    sdt: '0973122679',
    email: 'LIEN.LTK@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 20,
    hoTen: 'Phạm Thị Yến Thuận',
    maNv: '00006980',
    user: 'thuanpty',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Thủ quỹ',
    sdt: '0917900250',
    email: 'THUANPTY@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 21,
    hoTen: 'Nguyễn Thị Thủy',
    maNv: '00006994',
    user: 'thuynt400',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Thủ quỹ',
    sdt: '0948422368',
    email: 'THUYNT400@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 22,
    hoTen: 'Tạ Hà Thu',
    maNv: '00015042',
    user: 'thuth',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0949128737',
    email: 'THUTH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 23,
    hoTen: 'Vũ Thị Hải Yến',
    maNv: '00015048',
    user: 'yenvth',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0915378184',
    email: 'YENVTH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 24,
    hoTen: 'Đoàn Thị Hải Phượng',
    maNv: '00015062',
    user: 'dthphuong',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0979051287',
    email: 'DTHPHUONG@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 25,
    hoTen: 'Trần Hoàng Oanh',
    maNv: '00015065',
    user: 'oanh.th',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Nhân viên kế toán tài chính',
    sdt: '0912872173',
    email: 'OANH.TH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 26,
    hoTen: 'Đinh Thị Lệ Tuyết',
    maNv: '00015068',
    user: 'tuyetdtl',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Thủ kho',
    sdt: '0344790810',
    email: 'TUYETDTL@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 27,
    hoTen: 'Trương Thanh Quý',
    maNv: '00021989',
    user: 'ttquy',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Phó phòng Dịch vụ KH (Kế toán)',
    sdt: '0916884849',
    email: 'TTQUY@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 28,
    hoTen: 'Cù Thế Anh',
    maNv: '00030000',
    user: 'anhct',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Thủ quỹ',
    sdt: '0977935552',
    email: 'ANHCT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 29,
    hoTen: 'Lê Thị Ngọc Anh',
    maNv: '00030628',
    user: 'anhltn1',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0948326676',
    email: 'ANHLTN1@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 30,
    hoTen: 'Nguyễn Thị Huế',
    maNv: '00038210',
    user: 'huent14',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0966877969',
    email: 'HUENT14@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 31,
    hoTen: 'Lê Thị Mỹ Lộc',
    maNv: '00041358',
    user: 'locltm',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0946894152',
    email: 'LOCLTM@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 32,
    hoTen: 'Thái Thị Thủy',
    maNv: '00041361',
    user: 'thuytt18',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0973710152',
    email: 'THUYTT18@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 33,
    hoTen: 'Phạm Hương Ly',
    maNv: '00051875',
    user: 'phly',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0367123462',
    email: 'PHLY@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 34,
    hoTen: 'Nguyễn Trọng Đức',
    maNv: '00053550',
    user: 'ducnt4',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'Kỹ sư Điện toán',
    sdt: '0943882109',
    email: 'DUCNT4@VIETINBANK.VN',
    role: 'ADMIN',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 35,
    hoTen: 'Hoàng Linh Chi',
    maNv: '00055890',
    user: 'chihl',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng DVKH',
    viTri: 'GDV độc lập',
    sdt: '0981234567',
    email: 'CHIHL@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 36,
    hoTen: 'Nguyễn Đình Quang',
    maNv: '00006988',
    user: 'ndquang',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Phó phòng KHDN',
    sdt: '0916889869',
    email: 'NDQUANG@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 37,
    hoTen: 'Nguyễn Thị Thu Thủy',
    maNv: '00015046',
    user: 'thuyntt400',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0917905596',
    email: 'THUYNTT400@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 38,
    hoTen: 'Phan Văn Anh',
    maNv: '00030623',
    user: 'pv.anh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Phó phòng KHDN',
    sdt: '0963804422',
    email: 'PV.ANH@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 39,
    hoTen: 'Ngô Thị Thúy Vân',
    maNv: '00038213',
    user: 'vanntt9',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0387811182',
    email: 'VANNTT9@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 40,
    hoTen: 'Trần Thanh Phong',
    maNv: '00038221',
    user: 'phongtt1',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0985123691',
    email: 'PHONGTT1@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 41,
    hoTen: 'Trần Thị Lĩnh',
    maNv: '00041326',
    user: 'linhtt10',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KH Doanh nghiệp Lớn',
    sdt: '0907750968',
    email: 'LINHTT10@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 42,
    hoTen: 'Phạm Nguyễn Phương Anh',
    maNv: '00044380',
    user: 'anhpnp',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0388653231',
    email: 'ANHPNP@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 43,
    hoTen: 'Mai Hoàng Nguyên',
    maNv: '00046626',
    user: 'nguyenmh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KH Doanh nghiệp Lớn',
    sdt: '0917996737',
    email: 'NGUYENMH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 44,
    hoTen: 'Trịnh Thị Phương Thúy',
    maNv: '00049281',
    user: 'thuy.ttp',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0833653427',
    email: 'THUY.TTP@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 45,
    hoTen: 'Nguyễn Thanh Hoa',
    maNv: '00049301',
    user: 'hoant28',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0352892688',
    email: 'HOANT28@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 46,
    hoTen: 'Đường Hoàng Giang',
    maNv: '00050013',
    user: 'giangdh3',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0985421738',
    email: 'GIANGDH3@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 47,
    hoTen: 'Nguyễn Thị Ngọc',
    maNv: '00055888',
    user: 'ngocnt11',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0356507212',
    email: 'NGOCNT11@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 48,
    hoTen: 'Phạm Thu Hà',
    maNv: '00057240',
    user: 'hapt20',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0946861912',
    email: 'HAPT20@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 49,
    hoTen: 'Trần Lan Anh',
    maNv: '00059438',
    user: 'tlanh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0886320500',
    email: 'TLANH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 50,
    hoTen: 'Đỗ Trường Thọ',
    maNv: '00006945',
    user: 'thodt',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'Phó phòng Bán lẻ',
    sdt: '0947778686',
    email: 'THODT@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 51,
    hoTen: 'Hoàng Minh Sơn',
    maNv: '00015071',
    user: 'sonhm',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'Phó phòng Bán lẻ',
    sdt: '0917683258',
    email: 'SONHM@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 52,
    hoTen: 'Mai Như Thế',
    maNv: '00017400',
    user: 'themn',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0946331183',
    email: 'THEMN@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 53,
    hoTen: 'Hoàng Thị Thơ',
    maNv: '00026273',
    user: 'thoht',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'Phó phòng Bán lẻ',
    sdt: '0389971051',
    email: 'THOHT@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 54,
    hoTen: 'Dương Vân Lan Anh',
    maNv: '00030624',
    user: 'anhdvl',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0838189555',
    email: 'ANHDVL@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 55,
    hoTen: 'Nguyễn Quang Tùng',
    maNv: '00041584',
    user: 'tungnq1',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0962603969',
    email: 'TUNGNQ1@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 56,
    hoTen: 'Vũ Thị Lan Hương',
    maNv: '00043031',
    user: 'huongvtl2',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0916868292',
    email: 'HUONGVTL2@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 57,
    hoTen: 'Nguyễn Thị Thu Thủy',
    maNv: '00044407',
    user: 'thuyntt39',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0979675819',
    email: 'THUYNTT39@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 58,
    hoTen: 'Hà Đăng Tuấn Linh',
    maNv: '00046627',
    user: 'linhhdt',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0945027445',
    email: 'LINHHDT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 59,
    hoTen: 'Phạm Thị Mai',
    maNv: '00046796',
    user: 'maipt1',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0946148548',
    email: 'MAIPT1@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 60,
    hoTen: 'Đinh Lê Hoài Thu',
    maNv: '00049307',
    user: 'thudlh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0858891998',
    email: 'THUDLH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 61,
    hoTen: 'Nguyễn Vũ Diệu Linh',
    maNv: '00055886',
    user: 'linhnvd',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0343639846',
    email: 'LINHNVD@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 62,
    hoTen: 'Hoàng Hương Ly',
    maNv: '00057244',
    user: 'hh.ly',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0942255119',
    email: 'HH.LY@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 63,
    hoTen: 'Đỗ Văn Tấn Dũng',
    maNv: '00059439',
    user: 'dungdvt',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0886681768',
    email: 'DUNGDVT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 64,
    hoTen: 'Trương Mai Hoa',
    maNv: '00059748',
    user: 'hoatm',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0329896592',
    email: 'HOATM@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 65,
    hoTen: 'Nguyễn Kháng Chiến',
    maNv: '00006928',
    user: 'chien.nk',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng HTTD',
    viTri: 'Phó phòng Hỗ trợ tín dụng',
    sdt: '0983648217',
    email: 'CHIEN.NK@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 66,
    hoTen: 'Bùi Quý Dương',
    maNv: '00006985',
    user: 'duong.bq',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng HTTD',
    viTri: 'Hỗ trợ tín dụng 1',
    sdt: '0902250555',
    email: 'DUONG.BQ@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 67,
    hoTen: 'Nguyễn Tiến Cương',
    maNv: '00006997',
    user: 'cuong.nguyentien',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng HTTD',
    viTri: 'Trưởng phòng Hỗ trợ tín dụng',
    sdt: '0913012267',
    email: 'CUONG.NGUYENTIEN@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 68,
    hoTen: 'Vũ Hữu Chuyên',
    maNv: '00017401',
    user: 'chuyenvh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng HTTD',
    viTri: 'Hỗ trợ tín dụng 1',
    sdt: '0977939079',
    email: 'CHUYENVH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 69,
    hoTen: 'Lê Thị Thanh Phương',
    maNv: '00024260',
    user: 'phuong.lethithanh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng HTTD',
    viTri: 'Hỗ trợ tín dụng 1',
    sdt: '0916569198',
    email: 'PHUONG.LETHITHANH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 70,
    hoTen: 'Dương Phú Đô',
    maNv: '00033371',
    user: 'dodp',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng HTTD',
    viTri: 'Hỗ trợ tín dụng 1',
    sdt: '0989704402',
    email: 'DODP@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 71,
    hoTen: 'Phạm Đoàn Hương Giang',
    maNv: '00053396',
    user: 'giangpdh',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng HTTD',
    viTri: 'Hỗ trợ tín dụng 1',
    sdt: '0857992000',
    email: 'GIANGPDH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 72,
    hoTen: 'Phạm Thị Thu Phi Lan',
    maNv: '00006946',
    user: 'lan.pttp',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'Trưởng PGD Hỗn hợp',
    sdt: '0868180980',
    email: 'LAN.PTTP@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 73,
    hoTen: 'Vũ Thị Thu Hà',
    maNv: '00006964',
    user: 'vttha',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'Phó phòng PGD Hỗn hợp',
    sdt: '0915316350',
    email: 'VTTHA@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 74,
    hoTen: 'Đinh Thị Phương',
    maNv: '00026248',
    user: 'phuong.dt',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0916530111',
    email: 'PHUONG.DT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 75,
    hoTen: 'Bùi Thị Ánh Nguyệt',
    maNv: '00026813',
    user: 'nguyetbta',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'GDV độc lập',
    sdt: '0917059822',
    email: 'NGUYETBTA@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 76,
    hoTen: 'Trần Thị Thu Phương',
    maNv: '00033307',
    user: 'phuongttt6',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'GDV độc lập',
    sdt: '0975699489',
    email: 'PHUONGTTT6@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 77,
    hoTen: 'Phan Văn Long',
    maNv: '00038216',
    user: 'pv.long',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0964326993',
    email: 'PV.LONG@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 78,
    hoTen: 'Trần Minh Thu Huyền',
    maNv: '00041357',
    user: 'huyentmt',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0945800008',
    email: 'HUYENTMT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 79,
    hoTen: 'Lã Thu Huyền',
    maNv: '00044378',
    user: 'huyenlt5',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0979503598',
    email: 'HUYENLT5@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 80,
    hoTen: 'Văn Thị Hồng Nhung',
    maNv: '00046628',
    user: 'nhungvth3',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0912852997',
    email: 'NHUNGVTH3@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 81,
    hoTen: 'Nguyễn Thị Hồng Hạnh',
    maNv: '00055885',
    user: 'hanhnth14',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Ninh Thành',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0382267393',
    email: 'HANHNTH14@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 82,
    hoTen: 'Nghiêm Thị Hiền',
    maNv: '00006937',
    user: 'hien.nghiemthi',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'Phó phòng PGD Hỗn hợp',
    sdt: '0912829018',
    email: 'HIEN.NGHIEMTHI@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 83,
    hoTen: 'Đỗ Thị Mai Hương',
    maNv: '00006954',
    user: 'dtmhuong',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0912299962',
    email: 'DTMHUONG@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 84,
    hoTen: 'Trương Thị Hồng Hạnh',
    maNv: '00006956',
    user: 'tthhanh',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'Phó phòng PGD Hỗn hợp',
    sdt: '0949872383',
    email: 'TTHHANH@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 85,
    hoTen: 'Nguyễn Thị Ngọc Bích',
    maNv: '00021646',
    user: 'ntngocbich',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'GDV độc lập',
    sdt: '0914357689',
    email: 'NTNGOCBICH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 86,
    hoTen: 'Đinh Xuân Hòa',
    maNv: '00021994',
    user: 'dx.hoa',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'Phó phòng PGD Hỗn hợp',
    sdt: '0914260111',
    email: 'DX.HOA@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 87,
    hoTen: 'Phạm Thanh Đức',
    maNv: '00029596',
    user: 'ducpt',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0917295799',
    email: 'DUCPT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 88,
    hoTen: 'Đinh Mạnh Cường',
    maNv: '00030627',
    user: 'dmcuong',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0703936888',
    email: 'DMCUONG@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 89,
    hoTen: 'Nguyễn Thị Vân Anh',
    maNv: '00044404',
    user: 'anhntv10',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'GDV độc lập',
    sdt: '0981795099',
    email: 'ANHNTV10@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 90,
    hoTen: 'Nguyễn Thị Linh',
    maNv: '00049286',
    user: 'linhnt51',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0932566555',
    email: 'LINHNT51@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 91,
    hoTen: 'Đinh Ngọc Phong',
    maNv: '00049306',
    user: 'phongdn',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0912455777',
    email: 'PHONGDN@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 92,
    hoTen: 'Phạm Thanh Hằng',
    maNv: '00055891',
    user: 'hangpt14',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Gia Viễn',
    viTri: 'GDV độc lập',
    sdt: '0357681312',
    email: 'HANGPT14@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 93,
    hoTen: 'Đinh Thị Hồng Thúy',
    maNv: '00006951',
    user: 'dththuy',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'GDV độc lập',
    sdt: '0914768222',
    email: 'DTHTHUY@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 94,
    hoTen: 'Vũ Thị Thu Trang',
    maNv: '00006967',
    user: 'vtttrang',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'Trưởng PGD Hỗn hợp',
    sdt: '0905868298',
    email: 'VTTTRANG@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 95,
    hoTen: 'Đinh Thành Trung',
    maNv: '00015039',
    user: 'dt.trung',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'Phó phòng PGD Hỗn hợp',
    sdt: '0916123289',
    email: 'DT.TRUNG@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 96,
    hoTen: 'Nguyễn Thị Hạnh',
    maNv: '00026276',
    user: 'hanhnt1',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0973497421',
    email: 'HANHNT1@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 97,
    hoTen: 'Nguyễn Hoài Đức',
    maNv: '00026281',
    user: 'ducnh',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0911191162',
    email: 'DUCNH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 98,
    hoTen: 'Giang Ngọc Hiệp',
    maNv: '00041354',
    user: 'hiepgn',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0982168799',
    email: 'HIEPGN@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 99,
    hoTen: 'Phạm Hương Giang',
    maNv: '00041356',
    user: 'giangph1',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0977071195',
    email: 'GIANGPH1@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 100,
    hoTen: 'Nguyễn Thị Thắm',
    maNv: '00042178',
    user: 'thamnt10',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0941929411',
    email: 'THAMNT10@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 101,
    hoTen: 'Đào Thu Hương',
    maNv: '00046638',
    user: 'huongdt21',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Yên Khánh',
    viTri: 'GDV độc lập',
    sdt: '0989451194',
    email: 'HUONGDT21@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 102,
    hoTen: 'Đào Quang Hải',
    maNv: '00006998',
    user: 'haidq',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'Phó phòng PGD Hỗn hợp',
    sdt: '0915331339',
    email: 'HAIDQ@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 103,
    hoTen: 'Vũ Hồng Hưng',
    maNv: '00015051',
    user: 'hungvh',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0942526289',
    email: 'HUNGVH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 104,
    hoTen: 'Nguyễn Thị Thương Huyền',
    maNv: '00015063',
    user: 'huyenntt400',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'Phó phòng PGD Hỗn hợp',
    sdt: '0944125269',
    email: 'HUYENNTT400@VIETINBANK.VN',
    role: 'LANH_DAO',
    isLeader: true,
    trangThai: 'Hoạt động'
  },
  {
    stt: 105,
    hoTen: 'Lê Đức Anh',
    maNv: '00026294',
    user: 'ld.anh',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0946622934',
    email: 'LD.ANH@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 106,
    hoTen: 'Đào Mạnh Cường',
    maNv: '00041353',
    user: 'cuongdm4',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0943673697',
    email: 'CUONGDM4@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 107,
    hoTen: 'Đinh Công Tuấn',
    maNv: '00044408',
    user: 'tuandc',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0977839355',
    email: 'TUANDC@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 108,
    hoTen: 'Nguyễn Thị Mai',
    maNv: '00050587',
    user: 'maint11',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'GDV độc lập',
    sdt: '0983996615',
    email: 'MAINT11@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 109,
    hoTen: 'Phạm Thị Mến',
    maNv: '00054558',
    user: 'men.pt',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'GDV độc lập',
    sdt: '0964973674',
    email: 'MEN.PT@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 110,
    hoTen: 'Nguyễn Thị Hồng Ánh',
    maNv: '00059380',
    user: 'anhnth5',
    password: DEFAULT_PASSWORD,
    phongBan: 'PGD Kim Sơn',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0865103662',
    email: 'ANHNTH5@VIETINBANK.VN',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 111,
    hoTen: 'Vũ Huyền Linh',
    maNv: '00060488',
    user: 'linhvh3',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng Bán lẻ',
    viTri: 'CB QHKH bán lẻ',
    sdt: '0865103663',
    email: 'linhvh3@vietinbank.vn',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  },
  {
    stt: 112,
    hoTen: 'Nguyễn Thị Thu Hiền',
    maNv: '00060487',
    user: 'hienntt36',
    password: DEFAULT_PASSWORD,
    phongBan: 'Phòng KHDN',
    viTri: 'Quan hệ KHDN Vừa & Nhỏ',
    sdt: '0865103664',
    email: 'hienntt36@vietinbank.vn',
    role: 'QHKH',
    isLeader: false,
    trangThai: 'Hoạt động'
  }
];
